my_dict={'Milana': 2012, 'Radmila': 2013, 'Kamila': 2021}
print(my_dict)
print(my_dict['Milana'])
print(my_dict.get('Papa'))
my_dict.update({'Mama':1980,'Deda':1950})
print(my_dict)
a = my_dict.pop('Deda')
print(my_dict)
print(a)
my_set = {5,6,7,8,5,6,False,(4,5,6)}
print(my_set)
print(my_set.add('a'))
print(my_set.add('True'))
print(my_set)
print(my_set.remove(5))
print(my_set)